### ISSUE TITLE
feature/category

### ISSUE THREAD

**Issue by soyeonvv** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_BE#11]
# 📝 기능 개요

- 카테고리 관련 기능

## ✔️ TODO

- [x] 카테고리 생성
- [x] 카테고리 조회
- [x] 카테고리 수정
- [x] 카테고리 삭제
- [x] 카테고리 조회-수정 (사용자가 삭제한 카테고리 제외)
- [x] 날짜별 카테고리 조회
- [x] 카테고리 수정 로직 변경
