### ISSUE TITLE
feature/category-modify

### ISSUE THREAD

**Issue by soyeonvv** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_BE#30]
# 📝 기능 개요
Category 조회 기능 수정

## ✔️ TODO

- [x] is_club 칼럼 추가
- [x] 카테고리 조회, 클럽 카테고리 조회 api 나누기
- [x] Category, ClubMembers 1대1 매핑
