### ISSUE TITLE
feature/user

### ISSUE THREAD

**Issue by shin0112** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_BE#5]
# 📝 기능 개요

- user 기본 기능

## ✔️ TODO

- [x] 로그인
- [ ] 로그아웃
- [x] 회원 가입
  - [x] 비밀번호 인코딩
- [x] 회원 정보 조회
- [x] 회원 정보 수정
- [x] 회원 탈퇴
- [x] 아이디 중복 확인
